### ISSUE TITLE
Dbmaintain consider DB2 warnings as success script. 

### ISSUE THREAD

**Issue by epelaic** [DbMaintain/dbmaintain#20]
Hello,

Actually DB2 warnings are considered like a successful script exécution by dbmaintain (exit code 2), so it will be valuable de set the mininum exit code level in the dbmaintain.properties to asses the correct execution of the script and display command output again custom requirements.

If a create index generate warning it will be nice to notify the user to fix the script.
A simple thing will be to put the exit code at the end of the the exec statement in the logs and change the log level INFOS to WARN like this :

WARN: Executed newly added indexed script: incremental/01//01_init-ddl.sql (8073 ms) exit code : 2

Actually only exite code 4 & 8 generate an error and output command result.

Best regards,

Edo

ENV : I'am currently with dmaintain and dbmaintain-maven-plugin 2.4 / Jdk 7.

**Comment by remast** [comment]
We won't fix this as DB2 is not so much in our focus. If you want that fixed I suggest you make a pull request and we are happy to accept that.
