### ISSUE TITLE
Confusing warning message during 

### ISSUE THREAD

**Issue by thomasnikolay** [DbMaintain/dbmaintain#29]
https://github.com/DbMaintain/dbmaintain/blob/000314fb8bbcb5977ea41f363b56882ddf44aa8e/dbmaintain/src/main/java/org/dbmaintain/script/executedscriptinfo/impl/DefaultExecutedScriptInfoSource.java#L335

The level of the message 
`[markDatabaseAsUpToDate] WARNING: Executed scripts table "xxxx" doesn't exist yet or is invalid. A new one i s created automatically.`
is confusing because through the member autoCreateExecutedScriptsTable is this behavior accepted from the user. My recommendation is to reduce the log level to INFO. If you want, then I will do that.

**Comment by pSub** [comment]
Thanks! I've set the log level to info.

**Comment by thomasnikolay** [comment]
Thanks a lot :-)
