### ISSUE TITLE
A non unicode scripts does not archived correctly

### ISSUE THREAD

**Issue by Shikaka** [DbMaintain/dbmaintain#9]
Hi, 

build dbmaintain-2.6.0 from master
create test

scripts\repeatable\test.sql - win-1251 with Russian letters
`create or replace function test return varchar2 is begin return 'Тест 1251'; end;
/`

set `dbMaintainer.script.encoding=WINDOWS-1251` in dbmaintain.properties

call `dbmaintain.bat createScriptArchive archivename.jar -config dbmaintain.properties` + `dbmaintain.bat updateDatabase archivename.jar -config dbmaintain.properties`

Result of `select test from dual` is `"5AB 1251` - bad encoding

if run dbmaintain with scriptdir directly call `dbmaintain.bat updateDatabase scriptdir -config dbmaintain.properties`
Then result would be normal `Тест 1251`

**Comment by pSub** [comment]
Closing as it seems to be fixed. Please reopen if the error persists.
